### ISSUE TITLE
data mapper

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/hapi-views#3]
pass in object to map request data to the view data.  Use something like `_.get` against request object.

```yaml
data:
  global: 'pre.global'
  isTest: 'query.test'
```

so the view can now use `{{global.blah}}` and `{{isTest}}`
